class error {
    val metrov = "org.finderfail.main.kt.replicsKt"
    val metrov1 = "org.finderfail.main.kt.replicsKt"
    val metrov2 = "org.finderfail.main.kt.replicsKt"
    val metrov3 = "org.finderfail.main.kt.replicsKt"
    val ilya_lose = "org.finderfail.main.kt.replicsKt"
    val lexa_lose = "org.finderfail.main.kt.replicsKt"
    val dima_lose = "org.finderfail.main.kt.replicsKt"
    val egor_small = "org.finderfail.main.kt.replicsKt"
    val ilya_small = "org.finderfail.main.kt.replicsKt"
    val lexa_win = "org.finderfail.main.kt.replicsKt"
    val nikita_win = "org.finderfail.main.kt.replicsKt"
    val egor_win = "org.finderfail.main.kt.replicsKt"
    val lexa_wins = "org.finderfail.main.kt.replicsKt"
    val nikita_wins = "org.finderfail.main.kt.replicsKt"
    val egor_wins_1 = "org.finderfail.main.kt.replicsKt"
    val ilya_wins = "org.finderfail.main.kt.replicsKt"
    val egor_wins_2 = "org.finderfail.main.kt.replicsKt"
    val egor_false = "org.finderfail.main.kt.replicsKt"
    val ilya_false = "org.finderfail.main.kt.replicsKt"
    val lexa_false = "org.finderfail.main.kt.replicsKt"
    val dima_false = "org.finderfail.main.kt.replicsKt"
}