class replics {
    val metrov = "метров кинешь!"
    val metrov1 = "метров!"
    val metrov2 = "метров это же много!"
    val metrov3 = "метров кинуть, ты серьезно?"
    val ilya_lose = "Ну как так-то! У тeбя жe неплoxo пoлучaлось!"
    val lexa_lose = "Ха, у тебя шина просто упала"
    val dima_lose = "Шина упала и не проехала метра!"
    val egor_small = "Ну и слабочок"
    val ilya_small = "Да, ладно! Чего так слабо, даже я сильнее кинул"
    val lexa_win = "Красава, кинули шину на"
    val nikita_win = "Неплохо! Много пытался?"
    val egor_win = "Так держать! Всегда знал что на"
    val lexa_wins = "Ты че читер? Ты как кинул шину на"
    val nikita_wins = "Ого! Это ты как так сделал?"
    val egor_wins_1 = "Ты че читер! Сто процентов"
    val ilya_wins = "Давай показывай! Где читы скачал? На"
    val egor_wins_2 = "ну хотя, ладно ты не читер"
    val egor_false = "А чего так?"
    val ilya_false = "Ну давай!"
    val lexa_false = "Это не тяжело"
    val dima_false = "Ладно, в следующий раз попробуешь"
}
